---
packages:
  - name: abook
    features: [email]
  - name: cyrus-sasl-xoauth2-git
    features: [email]
  - name: gmailctl
    features: [work]
  - name: lynx
    features: [email]
  - name: mpc
    features: [mopidy]
  - name: msmtp
    features: [email]
  - name: mutt-wizard
    features: [email]
  - name: neomutt
    features: [email]
  - name: notmuch
    features: [email]
  - name: python-tidalapi
    features: [desktop, mopidy]
  - name: urlview
    features: [desktop, email]
