#!/usr/bin/env bash

chez=$(chezmoi data)
builds="$HOME/.local/share/container-builds"

build() {
    local name="$1"
    local context="${2:-$builds}"
    podman build --layers -t "localhost/$name" -f "$builds/Containerfile.$name" "$context"
}

build beets "$HOME"
