#!/usr/bin/env bash

chez=$(chezmoi data)
builds="$HOME/.local/share/container-builds"

build() {
    local name="$1"
    local context="${2:-$builds}"
    podman build --layers -t "localhost/$name" -f "$builds/Containerfile.$name" "$context"
}

if echo "$chez" | jq -e '.taskwarrior == true' > /dev/null; then
    build bugwarrior
    build vit
fi

if echo "$chez" | jq -e '.work == true' > /dev/null; then
    build gcalcli
fi

build beets "$HOME"

if echo "$chez" | jq -e '.email == true' > /dev/null; then
    build mutt-oauth2
fi
