#!/usr/bin/env bash

cd /home/joshmock/.local/share/chezmoi/cron || exit 1

restow() {
  pkg=$1
  echo "Updating cron jobs in /etc/cron.$pkg"
  sudo stow -Rv --target "/etc/cron.$pkg" "$pkg"
}

for pkg in daily hourly; do
  stow --simulate -v --target "/etc/cron.$pkg" "$pkg" 2>&1 | \
    grep 'LINK' > /dev/null && \
    restow $pkg || echo > /dev/null
done
