#!/usr/bin/env bash

chez=$(chezmoi data)
pypkgs=$(pipx list --json)

if echo "$chez" | jq -e '.taskwarrior == true'; then
  # bugwarrior doesn't work on 3.12 yet
  if echo "$pypkgs" | jq -e '.venvs | has("bugwarrior")'; then
    pipx upgrade bugwarrior
  else
    pipx install --preinstall=setuptools --fetch-missing-python --python 3.11 bugwarrior
  fi

  # vit doesn't work on 3.12 yet
  if echo "$pypkgs" | jq -e '.venvs | has("vit")'; then
    pipx upgrade vit
  else
    pipx install --fetch-missing-python --python 3.11 vit
  fi
fi

# install gcalcli
if echo "$chez" | jq -e '.work == true'; then
  if echo "$pypkgs" | jq -e '.venvs | has("gcalcli")'; then
    pipx upgrade gcalcli
  else
    pipx install --fetch-missing-python --python 3.12 gcalcli
  fi
fi

# install mopidy
if echo "$chez" | jq -e '.mopidy == true'; then
  if echo "$pypkgs" | jq -e '.venvs | has("mopidy")'; then
    pipx upgrade mopidy --include-injected
  else
    pipx install --fetch-missing-python --python 3.12 Mopidy
    # gst-python
    pipx inject Mopidy \
      Mopidy-Bandcamp \
      Mopidy-Beets \
      Mopidy-Iris \
      Mopidy-Jellyfin \
      Mopidy-MPD \
      Mopidy-MPRIS \
      Mopidy-Scrobbler \
      Mopidy-SoundCloud \
      Mopidy-YouTube \
      mopidy-tidal \
      Mopidy-InternetArchive \
      Mopidy-Mowecl \
      Mopidy-Local \
      PyGObject
  fi
fi

# install beets
if echo "$pypkgs" | jq -e '.venvs | has("beets")'; then
  # pipx upgrade beets --include-injected
  echo "beets already installed"
else
  pipx install --fetch-missing-python --python 3.13 'beets[lastgenre,fetchart]==2.5.1'
fi

# install mutt-oauth2
if echo "$chez" | jq -e '.email == true'; then
  if echo "$pypkgs" | jq -e '.venvs | has("mutt-oauth2")'; then
    pipx upgrade mutt-oauth2
  else
    pipx install mutt-oauth2
  fi
fi
