format = """\
  $cmd_duration\
  $directory\
  $git_branch\
  $git_state\
  $git_status\
  $python\
  $rust\
  $line_break\
  $character\
"""

[directory]
truncate_length = 3
style = "bold #999999"

[git_branch]
style = "bold #566C82"

[git_status]
style = "#AB5454"

[python]
style = "#AAEEAA"
