[pyprland]
plugins = ["scratchpads", "menubar", "system_notifier"]

[scratchpads.tasks]
command = "/usr/bin/kitty --session ~/.config/kitty/scratchpad-session.conf --class kitty-scratchpad"
class = "kitty-scratchpad"
size = "70% 70%"
animation = "fromTop"

[scratchpads.volume]
command = "pavucontrol"
class = "org.pulseaudio.pavucontrol"
size = "70% 60%"
animation = "fromTop"
lazy = true

[scratchpads.system]
command = "kitty --hold=no --app-id=kitty-btop btop"
class = "kitty-btop"
size = "70% 70%"
animation = "fromTop"
lazy = true

[menubar]
command = "noctalia"
monitors = ["eDP-1", "DP-1", "DP-2", "DP-3"]

[system_notifier]
use_notify_send = true

[[system_notifier.sources]]
command = "journalctl -fx"
parser = "journal"

[[system_notifier.parsers.journal]]
pattern = "backup\\.service:.*FAILURE$"
filter = "s/.*/Backup failed/"
color = "#FF0000"
duration = 20

[[system_notifier.parsers.journal]]
pattern = "backup\\.service: Failed with result"
filter = "s/.*/Backup failed/"
color = "#FF0000"
duration = 20

[[system_notifier.parsers.journal]]
pattern = "bugwarrior.*ERROR"
filter = "s/.*/Bugwarrior sync failed/"
color = "#FF0000"
duration = 20

[[system_notifier.parsers.journal]]
pattern = "bugwarrior.*ERROR"
filter = "s/.*/Bugwarrior sync failed/"
color = "#FF0000"
duration = 20
