#!/usr/bin/env bash

input=$(cat)
if [ -z "$input" ]; then
  input='[General]
enableMiniWindow=false
enableWaylandShare=false
xwayland=true'
else
  input=$(echo "$input" | \
    sed 's/enableMiniWindow=true/enableMiniWindow=false/' | \
    sed 's/enableWaylandShare=true/enableWaylandShare=false/' | \
    sed 's/xwayland=false/xwayland=true/'
)
fi

echo "$input"
