FROM archlinux:base

RUN pacman -Sy --noconfirm archlinux-keyring \
  && pacman -Su --noconfirm \
  && pacman -S --noconfirm task git make nim gcc python python-pip python-emoji xdg-utils \
  && rm -rf /var/cache/pacman/pkg/*

RUN git clone https://github.com/jschlatow/taskopen.git /tmp/taskopen \
  && cd /tmp/taskopen \
  && make PREFIX=/usr \
  && make PREFIX=/usr install \
  && rm -rf /tmp/taskopen

RUN pip install --no-cache-dir --break-system-packages vit
