#!/usr/bin/env python3
import argparse
import json
import requests

parser = argparse.ArgumentParser(description='List items from Pocket')
parser.add_argument('--tag', help='Filter by tag')
parser.add_argument('--count', type=int, default=40)
parser.add_argument('--state', default='unread', choices=['unread', 'archive', 'all'])
parser.add_argument('--sort', default='newest', choices=['newest', 'oldest', 'title', 'site'])
args = parser.parse_args()

# get auth info
with open('/home/joshmock/.config/pocket/auth.json') as f:
    auth = json.loads(f.read())

res = requests.post('https://getpocket.com/v3/get', json={**auth, **vars(args)})

res.raise_for_status()

data = res.json()
for k, v in data['list'].items():
    print(v['resolved_title'] + ' ' + v['resolved_url'])
