[bootstrap.packages]
"pacman:kitty" = "latest"
"pacman:kitty-terminfo" = "latest"
"pacman:vlc" = "latest"
"pacman:vlc-plugins-all" = "latest"
# "aur:zeal-git" = "latest"
"pacman:slack-desktop" = "latest"
"pacman:obsidian" = "latest"
"pacman:firefox-developer-edition" = "latest"
"pacman:discord" = "latest"
"pacman:element-desktop" = "latest"
"pacman:1password" = "latest"
"pacman:vivaldi" = "latest"
"pacman:vivaldi-ffmpeg-codecs" = "latest"
