[settings]
disable_tools = ["lua", "python"]

[tools]
node = "latest"
bun = "latest"
nono = "latest"
"npm:@elastic/cli" = "latest"
"github:asciimoo/hister" = "latest"
"npm:agent-browser" = { version = "latest", postinstall = "agent-browser install" }
