# vim: ft=toml

[tools]
1password-cli = "latest"
ast-grep = "latest"
atuin = "latest"
bat = "latest"
btop = "latest"
bun = "latest"
delta = "latest"
difftastic = "latest"
direnv = "latest"
eza = "latest"
fd = "latest"
fzf = "latest"
gh = "latest"
git-lfs = "latest"
gping = "latest"
hyperfine = "latest"
jless = "latest"
jq = "latest"
jujutsu = "latest"
just = "latest"
lazygit = "latest"
lua = "latest"
node = "latest"
nono = "latest"
python = "latest"
rclone = "latest"
ripgrep = "latest"
starship = "latest"
tealdeer = "latest"
yazi = "latest"
yq = "latest"
yt-dlp = "latest"
uv = "latest"
"github:asciimoo/hister" = "latest"
"npm:agent-browser" = { version = "latest", postinstall = "agent-browser install" }
"github:ouch-org/ouch" = "latest"
"http:zp" = { version = "0.3.0", url = "https://raw.githubusercontent.com/EarthmanMuons/zmx-picker/v{{version}}/zp" }
"npm:@earendil-works/pi-coding-agent" = "latest"
