---
toggle_key: "OFF"
search_shortcut: "OFF"
search_trigger: "OFF"

matches:
  - trigger: "@@"
    replace: "josh@joshmock.com"

  - trigger: ":email"
    replace: "joshua.mock@elastic.co"

  - trigger: "bc"
    replace: "because"
    word: true
    propagate_case: true

  - trigger: "tho"
    replace: "though"
    word: true
    propagate_case: true

  - trigger: "gy"
    replace: "gotcha"
    word: true
    propagate_case: true

  - trigger: ":date"
    replace: "{{mydate}}"
    vars:
      - name: mydate
        type: date
        params:
          format: "%Y-%m-%d"
